name: Pimbi
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/pimbi-logo-apple.png
  min_sdk_android: 21